import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import test from "node:test";

import { PublicKey } from "@solana/web3.js";

import {
  BPF_LOADER_UPGRADEABLE_PROGRAM_ID,
  MAX_WRITE_PAYLOAD_BYTES,
  encodeLoaderV3Write,
  makeLoaderV3WriteInstruction,
} from "../../scripts/devnet/loader-v3-codec.mjs";

const BUFFER = new PublicKey("CT1DGjkt9t926L6SoFxiYJmzc18nMowpdw1WcZgWwbbW");
const AUTHORITY = new PublicKey("Avfvs1k6ttrBtqh83tFw5g3dhWncrjP5hj4D52kGNZGk");

function readFixture() {
  return JSON.parse(readFileSync("tests/fixtures/loader-v3-write-vectors.json", "utf8"));
}

function vectorPayload(vector) {
  if (vector.payloadHex !== undefined) {
    return Buffer.from(vector.payloadHex, "hex");
  }
  assert.deepEqual(vector.payloadPattern, {
    kind: "incrementing-modulo",
    modulo: 251,
    length: 1011,
  });
  return Buffer.from(Uint8Array.from(
    { length: vector.payloadPattern.length },
    (_, index) => index % vector.payloadPattern.modulo,
  ));
}

test("regenerates the committed fixture exactly from the independently pinned Rust crate", () => {
  const generated = spawnSync(
    "cargo",
    ["run", "--locked", "--quiet", "--manifest-path", "tools/loader-v3-vectors/Cargo.toml"],
    { encoding: "utf8", windowsHide: true },
  );
  assert.equal(generated.status, 0, generated.stderr);
  assert.deepEqual(JSON.parse(generated.stdout), readFixture());
});

test("records exact Agave 2.2.20 compatibility and required vector coverage", () => {
  const fixture = readFixture();
  assert.deepEqual(fixture.provenance, {
    agaveTag: "v2.2.20",
    agaveCommit: "df1f50cc0045157e099dcb047b853f611b6050d9",
    agaveWorkspaceDependency: "solana-loader-v3-interface = 5.0.0",
    interfaceCrate: "solana-loader-v3-interface",
    interfaceVersion: "5.0.0",
    interfaceChecksum: "6f7162a05b8b0773156b443bccd674ea78bb9aa406325b467ea78c06c99a63a2",
    enumVariant: "UpgradeableLoaderInstruction::Write",
    enumDiscriminant: 1,
    serialization: "bincode-1.3.3",
    generator: "tools/loader-v3-vectors",
  });
  assert.deepEqual(fixture.vectors.map(({ coverage }) => coverage), [
    "offset-zero",
    "non-zero-offset",
    "multi-byte-offset-boundary",
    "near-maximum-planned-payload",
  ]);
  assert.equal(fixture.vectors[0].offset, 0);
  assert.ok(fixture.vectors[1].offset > 0);
  assert.equal(fixture.vectors[2].offset, 256);
  assert.equal(vectorPayload(fixture.vectors[3]).length, 1011);
});

test("checks JavaScript codec output against pinned Rust fixture vectors", () => {
  const fixture = readFixture();
  assert.equal(fixture.provenance.interfaceCrate, "solana-loader-v3-interface");
  assert.equal(fixture.provenance.interfaceVersion, "5.0.0");
  for (const vector of fixture.vectors) {
    const payload = vectorPayload(vector);
    const encoded = encodeLoaderV3Write({ offset: vector.offset, bytes: payload });
    if (vector.instructionDataHex !== undefined) {
      assert.equal(encoded.toString("hex"), vector.instructionDataHex);
    } else {
      assert.equal(encoded.subarray(0, 16).toString("hex"), vector.instructionHeaderHex);
      assert.equal(encoded.length, vector.instructionLength);
    }
    const instruction = makeLoaderV3WriteInstruction({
      buffer: BUFFER,
      authority: AUTHORITY,
      offset: vector.offset,
      bytes: payload,
    });
    assert.equal(instruction.programId.toBase58(), vector.programId);
    assert.deepEqual(
      instruction.keys.map(({ pubkey, isSigner, isWritable }) => ({
        pubkey: pubkey.toBase58(),
        isSigner,
        isWritable,
      })),
      vector.accounts,
    );
  }
});

test("encodes the Agave-compatible loader-v3 Write instruction", () => {
  // bincode(UpgradeableLoaderInstruction::Write { offset: 0, bytes: [1,2,3] })
  // generated by tools/loader-v3-vectors pinned to solana-loader-v3-interface 5.0.0.
  assert.deepEqual(
    encodeLoaderV3Write({ offset: 0, bytes: Buffer.from([1, 2, 3]) }),
    Buffer.from([1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3]),
  );
});

test("creates the exact loader instruction account order and signer flags", () => {
  const instruction = makeLoaderV3WriteInstruction({
    buffer: BUFFER,
    authority: AUTHORITY,
    offset: 0x01020304,
    bytes: Buffer.from([9]),
  });
  assert.equal(instruction.programId.toBase58(), BPF_LOADER_UPGRADEABLE_PROGRAM_ID);
  assert.deepEqual(
    instruction.keys.map((key) => ({
      pubkey: key.pubkey.toBase58(),
      isSigner: key.isSigner,
      isWritable: key.isWritable,
    })),
    [
      { pubkey: BUFFER.toBase58(), isSigner: false, isWritable: true },
      { pubkey: AUTHORITY.toBase58(), isSigner: true, isWritable: false },
    ],
  );
  assert.deepEqual(
    instruction.data,
    Buffer.from([1, 0, 0, 0, 4, 3, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 9]),
  );
});

test("rejects malformed offsets and oversized payloads", () => {
  assert.throws(
    () => encodeLoaderV3Write({ offset: -1, bytes: Buffer.alloc(0) }),
    /offset/,
  );
  assert.throws(
    () => encodeLoaderV3Write({ offset: 2 ** 32, bytes: Buffer.alloc(0) }),
    /offset/,
  );
  assert.throws(
    () => encodeLoaderV3Write({ offset: 0, bytes: Buffer.alloc(MAX_WRITE_PAYLOAD_BYTES + 1) }),
    /payload/,
  );
});
